import "~/styles/globals.css";

import NavBar from "./_components/NavBar/NavBar";
import UpperFooter from "./_components/Footer/UpperFooter";
import LowerFooter from "./_components/Footer/LowerFooter";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex flex-col items-center">
        <NavBar />
        <TRPCReactProvider>{children}</TRPCReactProvider>
        <UpperFooter />
        <LowerFooter />
      </body>
    </html>
  );
}
